### ISSUE TITLE
Adding more than one local/offline device CA

### ISSUE THREAD

**Issue by mike-sul** [foundriesio/fioctl#118]
I, as a customer, would like to have a dedicated offline device/fleet CA for each group of my devices.
`fioctl keys ca create` creates one offline and one online device CA. `fioctl keys ca update` provides a mechanism to upload a device CA bundle to the OTA backend, but it doesn't provide any mechanisms for generation, signing, and appending of a new offline device CA to the device CA bundle.

**Comment by vkhoroz** [comment]
This was addressed by https://github.com/foundriesio/fioctl/pull/319.

Now the user can run `fioctl keys ca add-device-ca` to add more than 1 online/local device CAs.
