### ISSUE TITLE
Add a mechanism to logout which clears out ~/.config/fioctl.yaml

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/fioctl#120]
A developer may want to logout for a variety of reasons.  We should let them.

**Comment by mike-scott** [comment]
This avoids having to use the `rm ~/.config/fioctl.yaml` method of logging out.

**Comment by doanac** [comment]
@mike-scott - rather than remove the file, I've made a change that clears out all credentials.

**Comment by mike-scott** [comment]
You rule.  This is perfect.
