### ISSUE TITLE
targets prune parameter vs targets list information

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/fioctl#14]
The new display for `targets list -f <factory>` is fantastic, however it doesn't give the user the right information to pass to `targets prune` anymore.

An example `targets list`:
```
VERSION  TAGS    APPS     HARDWARE IDs
-------  ----    ----     ------------
...
33       devel   x-kiosk  raspberrypi3-64,raspberrypi4-64
34       devel   x-kiosk  raspberrypi3-64,raspberrypi4-64
35       master  x-kiosk  raspberrypi3-64,raspberrypi4-64
```

But `targets prune` needs the build numer + machine name.

**Comment by mike-scott** [comment]
Thinking about this.  What if we add the actual target -> platform build name in `targets show -f <factory> 35` command:

```
Tags:	master

TARGET NAME             OSTREE HASH - SHA256
-----------             --------------------
raspberrypi4-64-lmp-35  7dadb47786dfdb4e77775e7979e77aebbdddef97df73469c77cf74dfde9b6bde787bde1e7dcdf8efc779dbae9ed377fd
raspberrypi3-64-lmp-35  739e5ad35dfa73b6bcdb77dde3473d6f7d3cef569ef1cef9e7879ae9ddfbf7569ad1fef7738d9df5d73ce1fe396df736

DOCKER APP  VERSION
----------  -------
x-kiosk     x-kiosk.dockerapp-35
```

**Comment by doanac** [comment]
@mike-scott -  i think that might work perfectly. Its also pretty consistent with how the rest of the CLI works. I'll take a look at doing that.
