### ISSUE TITLE
BUG: fioctl waves rollout <group-name> doesn't complain about missing wave name

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/fioctl#146]
Expected behavior is for the fioctl command to complain about a missing wave name

**Comment by doanac** [comment]
I'm not sure how this can be recreated. The file hasn't changed since it was committed to git:
```
$ fioctl waves rollout foo
Error: accepts 2 arg(s), received 1
Usage:
  fioctl waves rollout <wave> <group> [flags]
```

**Comment by doanac** [comment]
@mike-scott - think i'm going to close this out unless you object?

**Comment by mike-scott** [comment]
Yep, go ahead and close.
