### ISSUE TITLE
fioctl login, fix msg

### ISSUE THREAD

**Issue by munoz0raul** [foundriesio/fioctl#158]
When login on fioctl, it shows:

```
fioctl login
Please visit:

  https://app.foundries.io/settings/tokens/

and create a new "Application Credential" to provide inputs below.
```

We can change it to https://app.foundries.io/settings/credentials/ instead.

Also, I think the README.md file is out of date. Maybe we should update it together.

**Comment by doanac** [comment]
already fixed. will go out in the next release of fioctl - https://github.com/foundriesio/fioctl/commit/a46d7658a99e714b780095bb640a8d08e2132d46
