### ISSUE TITLE
Release a semantic tag to update package version on pkg.dev

### ISSUE THREAD

**Issue by rafaelcn** [foundriesio/fioctl#191]
I found that the latest version of this client available through pkg.dev is 0.19.0; please look at this [answer ](https://stackoverflow.com/questions/60217151/how-to-release-updated-packages-for-go-mod-pkg-go-dev-consumers) and release a semantic tagged version of this client library.

After that, force pkg.dev update its version with the following command:

```
curl https://sum.golang.org/lookup/github.com/foundriesio/fioctl@v0.29.0
```

**Comment by doanac** [comment]
We've released v0.30.30. However, our go.mod uses a replace directive so simply running `go install` will still not work. I believe this is also why pkg.dev won't show docs for this.

**Comment by rafaelcn** [comment]
I just retried the command above.

```
[0] % curl https://sum.golang.org/lookup/github.com/foundriesio/fioctl@v0.30.0 
14374664
github.com/foundriesio/fioctl v0.30.0 h1:KzTImpEj2/08EOHB0PgksacHi04th4Na/SJpTltjubs=
github.com/foundriesio/fioctl v0.30.0/go.mod h1:P5Ns1vmy8ztfIJQTRqTp1tucfKeNfoVbqycIaGn0tuc=

go.sum database tree
14375376
QHShSxg8O783yHsmUkfXDbjw8CbyvEL10U0ecCAt1AM=

— sum.golang.org Az3grh1RVIsC/WSXi6HahKhNYW2fR1odcJIne+oTS/UNbbGJwiPYniDKoLKC4ykRnmWDwp1/PUw2M6plLKFUlkMWXAY=
```

it did update it on pkg.go.dev :-)

**Comment by rafaelcn** [comment]
Proof of update: https://pkg.go.dev/github.com/foundriesio/fioctl. I'll close this issue as solved, thanks @doanac.
