### ISSUE TITLE
fioctl on different branch

### ISSUE THREAD

**Issue by s-bruce13** [foundriesio/fioctl#237]
Hello Im currently using fioctl from the binaries provided in releases. 
I'd like to test some from the mcu-api branch. 
What are the steps to change this? I already cloned repository and switched branch but make build command doesnt work. 
Its not clear for me how to switch it.

**Comment by doanac** [comment]
`make build` is mainly for building all binaries for a release. You can build for a specific target with something like:
```
make fioctl-linux-amd64
```
The Makefile includes targets for: 
 * fioctl-linux-amd64
 * fioctl-linux-arm64
 * fioctl-linux-armv7
 * fioctl-windows-amd64
 * fioctl-darwin-amd64
 * fioctl-darwin-arm64

**Comment by s-bruce13** [comment]
Thanks for the quick reply. Yes I tried both in case i was doing something strange but i dont know if im missing a dependency:

$ make fioctl-windows-amd64
CGO_ENABLED=0 \
        GOOS=windows \
        GOARCH=amd64 \
                go build -ldflags "-X=github.com/foundriesio/fioctl/subcommands/version.Commit=v0.32.0-14-ge72c22a" -o bin/fioctl-windows-amd64 main.go
/usr/bin/sh: line 1: go: command not found
make: *** [fioctl-windows-amd64] Error 127


I search for the go command not found, but i only find information for ubuntu. Im using windows.

**Comment by doanac** [comment]
You'll need to install the golang compiler to build this project.

**Comment by StealthyCoder** [comment]
You can follow the instructions from [here](https://go.dev/doc/install) by clicking the `Windows` tab. That should get you going. :+1:

**Comment by s-bruce13** [comment]
got it, thanks so much for the quick replies!
