### ISSUE TITLE
fioctl with no feedback when send a file to device

### ISSUE THREAD

**Issue by munoz0raul** [foundriesio/fioctl#35]
When you send a new file to the device using fioctl the command do not return if the file has been successfully sent.

```
 munoz0raul $ fioctl devices config set homeassistant32 ibm.config="$(cat ibm.config)"
 munoz0raul $
```

**Comment by doanac** [comment]
The device picks up the config change asynchronously. You can run `fioctl devices config log <device>`. It includes an "applied at" field to show you when a given config change was applied
