### ISSUE TITLE
Use correct semantic versioning

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/fioctl#37]
I want to add the following information to the readme, it'd be nice if `go get` was the actual installation method, as this would allow people to update seamlessly as they would with an npm application or any other package manager. `go get` of course works on this repo, the problem is that the versions are labeled incompatibly with go packages which expect `v1.0` instead of simply `1.0` and all the release tags on this repo have no letter `v` behind their version number.

Here's our package. No versions are detected
https://pkg.go.dev/mod/github.com/foundriesio/fioctl?tab=versions

Whereas here's [mux](https://github.com/gorilla/mux) which is properly configured.
https://pkg.go.dev/github.com/gorilla/mux?tab=versions

```
## Installation

### Grab a [release binary](https://github.com/foundriesio/fioctl/releases)

Download a `go` executable for your OS from the [release page](https://github.com/foundriesio/fioctl/releases) 
and place the executable in a directory in your $PATH.

### Build from latest release via `go get`

~~~
`go get -u github.com/foundriesio/fioctl@latest`
~~~
```

**Comment by doanac** [comment]
similar idea, but i think we should model the install more like what kubectl does. its more analogous to what we do than mux.

**Comment by MatthewCroughan** [comment]
@doanac Yeah that's the good stuff. They really did give every possible method. `go get` is really building rather than an installation as you initially said, which is why a lot of Google's go packages do not suggest using `go get`. I suspect this also plugs into a lot of places that we're not yet considering based on the infrastructure of other Go applications, as well as the contribution guidelines for kubectl.

For example, the kubectl README states that your contributions must be:
> Go tools compliant (go get, go test, etc.). It needs to be vendorable somewhere else.

There must be other reasons to be compliant with the go get functionality other than just being able to shorthand reproduce builds via `go get fioctl@1.2` for example.

https://pkg.go.dev/k8s.io/kubernetes/pkg/kubectl?tab=doc

**Comment by MatthewCroughan** [comment]
In addition to prepending v, we also need to adhere to semantic versioning. The latest release `v0.11` needs to be `v0.11.0` for example, otherwise it doesn't adhere to the go module publishing guidelines, and thus does not work with some elements of the toolchain. 

https://blog.golang.org/publishing-go-modules

**Comment by MatthewCroughan** [comment]
This has been done inconsistently. 

v0.14.1 was correct
v0.8.1 was correct
v0.5.1 was correct

Though every other release/tag has removed the v0.0.x necessary for Fioctl to work with the golang packaging tooling, as well as anything else that would package it into any format, since semver has to be consistent in most systems.

@doanac Is there a pattern here that I'm not able to follow? How comes some releases in our release history have correct semver whereas the rest do not?

**Comment by rafaelcn** [comment]
I see this problem is related to the newly submitted issue #191. This is still a problem as the foundries client library has not been updated on pkg.dev.

**Comment by rafaelcn** [comment]
I even tried to forcefully update pkg.dev with its latest version but couldn't do it.

```
[0] % curl https://sum.golang.org/lookup/github.com/foundriesio/fioctl@v0.29.0
not found: github.com/foundriesio/fioctl@v0.29.0: invalid version: unknown revision v0.29.0%                                                                                                                         

[0] % curl https://sum.golang.org/lookup/github.com/foundriesio/fioctl@v0.29  
bad request: version "v0.29" is not canonical (wanted "v0.29.0")% 
```

**Comment by MatthewCroughan** [comment]
As an interesting tidbit, I added Fioctl to Nixpkgs a year ago here https://github.com/NixOS/nixpkgs/pull/115885

I corrected the semantic versioning in the compilation process, by ignoring the Makefile and setting the Go ldflags manually in the derivation like this

```
  buildFlagsArray = ''
    -ldflags=-s -w -X github.com/foundriesio/fioctl/subcommands/version.Commit=${src.rev}
  '';
```

It has been updating automatically and tracking every single release of this repository ever since, without my involvement.

`nix shell github:nixos/nixpkgs/nixos-21.05#fioctl` would get you an old version of Fioctl 0.17 for example, or you could just override the version of Fioctl you want to have. For example, to use my derivation to build the latest revision of Fioctl as of the time of writing:
`nix-shell -p 'fioctl.overrideAttrs (_: { src = builtins.fetchGit { url = "https://github.com/foundriesio/fioctl"; rev = "7fd8404cca6c59d48a123f1c1f21c2800bb6a849"; }; })'`

**Comment by rafaelcn** [comment]
Very interesting indeed, @MatthewCroughan. Unfortunately, I don't use NixOS, and I don't know what else to do to make this update on the official Go package proxy.

**Comment by rafaelcn** [comment]
hey @MatthewCroughan, the issue was solved. See #191 for more details.
