### ISSUE TITLE
Failing to input correct credentials with `fioctl login` fails subsequent attempts

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/fioctl#50]
If you were to provide the incorrect input to `fioctl login`, it will fail the next attempt to use `fioctl login`. with:

`ERROR: Unable to retrieve credentials: HTTP_400`

The user would then have to remove their `.config` before they could attempt to use `fioctl login` again.

**Comment by doanac** [comment]
@MatthewCroughan - i believe this is fixed. so i'm closing this out.
