### ISSUE TITLE
Fix cobra doc for target 'list' and 'show' subcommands

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/fioctl#59]
There is some confusion in the documentation regarding `<target>` use [here](https://ci.foundries.io/projects/fio-docs/builds/620/docs/artifacts/html/reference-manual/factory/fioctl/fioctl_targets_image.html#fioctl-targets-image) and the results of `fioctl targets list` [here](https://ci.foundries.io/projects/fio-docs/builds/620/docs/artifacts/html/reference-manual/factory/fioctl/fioctl_targets_list.html):

A user can't just run `fioctl targets list -f <factory>` and take the last value there like `1221` and plug that into `fioctl targets image 1221 -f <factory>`

You actually need to `fioctl targets show 1221 -f <factory>` and find the "Target Name" from that display and plug it into `fioctl targets image`

**Comment by doanac** [comment]
Commit 5eb5fdc4990999758598920c55c9f604c2db7bc8 helps some with this, but the Target Name vs Target Version issue still remains.
