### ISSUE TITLE
Ethereum cryptocurrency dependency?

### ISSUE THREAD

**Issue by AustinDeric** [foundriesio/fioctl#62]
Why is the fioctl tooling depending on the ethereum cryptocurrency protocol: https://github.com/foundriesio/fioctl/blob/a5c4f5a7c6c54748d94c29b2439c4107841929ba/go.mod#L9

https://github.com/ethereum/go-ethereum

This link gives a 404 error: https://github.com/foundriesio/fioctl/blob/372b0a01eae8f043409f2b57db4d180779fe1c8e/subcommands/devices/config_set.go#L16

**Comment by doanac** [comment]
We use the library for ECIES encryption. Here's a blog about it: https://foundries.io/insights/blog/2020/04/01/200401-fioconfig/

The link you tried is for golang tooling. The actual web url is here https://github.com/ethereum/go-ethereum/tree/master/crypto/ecies

**Comment by AustinDeric** [comment]
oh fantastic, thanks!
